-- Practice --

CREATE TABLE STUDENTS(
IDNO CHAR(11),
NAME VARCHAR(30),
DOB DATE,
CGPA NUMERIC(4,2),
AGE NUMERIC(2)
);

INSERT INTO STUDENTS
VALUES('2016B4A7891','NDS','5-MAY-98',0009.20,20);

INSERT INTO STUDENTS(NAME, IDNO, AGE)
VALUES('NDS2','2016B4A7891',20);

-- not null
CREATE TABLE STAFF(
SID NUMERIC(10) NOT NULL,
NAME VARCHAR(20),
DEPT VARCHAR(15)
);

INSERT INTO STAFF(NAME,DEPT)
VALUES('KRSIHNA','PSD');

--unique and not null unique
CREATE TABLE COURSE(
COMPCODE NUMERIC(4) UNIQUE,
COURSENO VARCHAR(9) NOT NULL UNIQUE,
COURSE_NAME VARCHAR(20),
UNITS NUMERIC(2) NOT NULL
);

DROP TABLE COURSE; --deletes the table

CREATE TABLE COURSE(
COMPCODE NUMERIC(4),
COURSENO VARCHAR(9) NOT NULL,
COURSE_NAME VARCHAR(20),
UNITS NUMERIC(2) NOT NULL,
UNIQUE(COMPCODE,COURSENO)  --table level constraint
);

--primary key = not null + unique
CREATE TABLE EMPLOYEE(
EMPID NUMERIC(4) PRIMARY KEY,
NAME VARCHAR(30) NOT NULL
);

CREATE TABLE REGISTERED(
COURSENO VARCHAR(9),
IDNO CHAR(13),
GRADE VARCHAR(10),
PRIMARY KEY(COURSENO, IDNO)
);

-- naming a constraint
CREATE TABLE REGISTERED(
COURSENO VARCHAR(9),
IDNO CHAR(13),
GRADE VARCHAR(10),
CONSTRAINT PK_REGISTERED PRIMARY KEY(COURSENO, IDNO)
);

--foreign key
DROP TABLE STUDENTS;
DROP TABLE COURSE;

CREATE TABLE STUDENTS(
IDNO CHAR(13),
NAME VARCHAR(30),
DOB DATE,
CGPA NUMERIC(4,2),
AGE NUMERIC(2),
CONSTRAINT PK_STUDENTS PRIMARY KEY(IDNO)
);

CREATE TABLE COURSE(
COMPCODE NUMERIC(4),
COURSENO VARCHAR(9) NOT NULL,
COURSE_NAME VARCHAR(20),
UNITS NUMERIC(2) NOT NULL,
CONSTRAINT UN_COURSE UNIQUE(COMPCODE,COURSENO),
CONSTRAINT PK_COURSE PRIMARY KEY(COURSENO)
);

CREATE TABLE REGISTERED1(
COURSENO VARCHAR(9) REFERENCES COURSE,  --column level FK
IDNO CHAR(13) REFERENCES STUDENTS,
GRADE VARCHAR(10),
PRIMARY KEY(COURSENO,IDNO)
);

CREATE TABLE REGISTERED2(
COURSENO VARCHAR(9),
IDNO CHAR(13),
GRADE VARCHAR(10),
CONSTRAINT PK_REGISTERED PRIMARY KEY(COURSENO, IDNO),
CONSTRAINT FK_CNO FOREIGN KEY(COURSENO) REFERENCES COURSE,
CONSTRAINT FK_IDNO FOREIGN KEY(IDNO) REFERENCES STUDENTS
);

DROP TABLE REGISTERED2;

CREATE TABLE REGISTERED2(
COURSENO VARCHAR(9),
IDNO CHAR(13),
GRADE VARCHAR(10),
CONSTRAINT PK_REGISTERED PRIMARY KEY(COURSENO, IDNO),
CONSTRAINT FK_CNO FOREIGN KEY(COURSENO) REFERENCES COURSE ON DELETE CASCADE,
CONSTRAINT FK_IDNO FOREIGN KEY(IDNO) REFERENCES STUDENTS ON DELETE CASCADE
);

--check constraint
CREATE TABLE STUDENT1(
IDNO CHAR(13) PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
CGPA NUMERIC(4,2) CHECK(CGPA >= 2 AND CGPA <= 10), -- CGPA CONSTRAINT
ROOMNO NUMERIC(3) CHECK(ROOMNO >99),
HOSTEL_CODE VARCHAR(2) CHECK(HOSTEL_CODE IN ('VK','RP','MB'))
);

--listing tables
SELECT * FROM STUDENTS;

--creating table from other table
SELECT * INTO STU_COPY FROM STUDENTS;

SELECT IDNO,NAME
INTO STU_COPY1
FROM STUDENTS;

--alter table
ALTER TABLE STAFF
ADD EMAIL VARCHAR(20);

ALTER TABLE STUDENTS
ADD HOSTEL VARCHAR(20);

ALTER TABLE STAFF
ALTER COLUMN EMAIL VARCHAR(50);

ALTER TABLE STAFF
DROP COLUMN EMAIL;

ALTER TABLE STUDENTS
ADD CONSTRAINT AGECHECK CHECK(AGE>15);

ALTER TABLE COURSE
DROP CONSTRAINT UN_COURSE;


--Exercise--
exec sp_MSforeachtable "declare @name nvarchar(max); set @name = parsename('?', 1); exec
sp_MSdropconstraints @name";
exec sp_MSforeachtable "drop table ?";

CREATE TABLE CATEGORY_DETAILS(
CATEGORY_ID NUMERIC(2),
CATEGORY_NAME VARCHAR(30)
);

CREATE TABLE SUB_CATEGORY_DETAILS(
SUB_CATEGORY_ID NUMERIC(2),
CATEGORY_ID NUMERIC(2),
SUB_CATEGORY_NAME VARCHAR(30)
);

CREATE TABLE PRODUCT_DETAILS(
PRODUCT_ID NUMERIC(6),
CATEGORY_ID NUMERIC(2),
SUB_CATEGORY_ID NUMERIC(2),
PRODUCT_NAME VARCHAR(30)
);

--1
ALTER TABLE CATEGORY_DETAILS
ALTER COLUMN CATEGORY_ID NUMERIC(2) NOT NULL;

ALTER TABLE CATEGORY_DETAILS
ADD PRIMARY KEY(CATEGORY_ID);

--2
ALTER TABLE SUB_CATEGORY_DETAILS
ALTER COLUMN SUB_CATEGORY_ID NUMERIC(2) NOT NULL;

ALTER TABLE SUB_CATEGORY_DETAILS
ADD CONSTRAINT PK_SCD PRIMARY KEY(SUB_CATEGORY_ID);

--3
ALTER TABLE SUB_CATEGORY_DETAILS
ADD CONSTRAINT FK_SCD FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_DETAILS;

--4
ALTER TABLE PRODUCT_DETAILS
ALTER COLUMN PRODUCT_ID NUMERIC(6) NOT NULL;

ALTER TABLE PRODUCT_DETAILS 
ADD CONSTRAINT PK_PD PRIMARY KEY(PRODUCT_ID),
	CONSTRAINT FK_CID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_DETAILS(CATEGORY_ID),
	CONSTRAINT FK_SCID FOREIGN KEY(SUB_CATEGORY_ID) REFERENCES SUB_CATEGORY_DETAILS(SUB_CATEGORY_ID);

--5
ALTER TABLE PRODUCT_DETAILS
ADD PRICE NUMERIC(2);

--6
ALTER TABLE PRODUCT_DETAILS
ALTER COLUMN PRICE NUMERIC(6,2);

--7
INSERT INTO PRODUCT_DETAILS (PRODUCT_ID, CATEGORY_ID, SUB_CATEGORY_ID,
PRODUCT_NAME, PRICE)VALUES (111111,11,12,'WATER',32);
INSERT INTO PRODUCT_DETAILS (PRODUCT_ID, CATEGORY_ID, SUB_CATEGORY_ID,
PRODUCT_NAME, PRICE)VALUES (111112,12,13,'CRISPS',23);
INSERT INTO PRODUCT_DETAILS (PRODUCT_ID, CATEGORY_ID, SUB_CATEGORY_ID,
PRODUCT_NAME, PRICE)VALUES (111113,13,14,'SOAP',20);
INSERT INTO PRODUCT_DETAILS (PRODUCT_ID, CATEGORY_ID, SUB_CATEGORY_ID,
PRODUCT_NAME, PRICE)VALUES (111114,14,15,'MAGGI',10);

SELECT * FROM PRODUCT_DETAILS;

--8
ALTER TABLE PRODUCT_DETAILS
DROP COLUMN PRICE;

--9 PROB
/*ALTER TABLE PRODUCT_DETAILS
ADD BRANDNAME VARCHAR(20) NOT NULL;*/

ALTER TABLE PRODUCT_DETAILS
ADD BRANDNAME VARCHAR(20);

SELECT * FROM PRODUCT_DETAILS;

--10
EXEC SP_RENAME 'CATEGORY_DETAILS','CAT_DT';


--CASE STUDY--
CREATE TABLE DEPARTMENTS(
CODE CHAR(5) PRIMARY KEY,
NAME VARCHAR(30),
MANAGERID NUMERIC(9),
SUBDEPTOF CHAR(5)
);

CREATE TABLE EMPLOYEES(
EMPLOYEEID NUMERIC(9) PRIMARY KEY,
FIRSTNAME VARCHAR(10),
LASTNAME VARCHAR(20),
DEPTCODE CHAR(5) REFERENCES DEPARTMENTS(CODE),
SALARY NUMERIC(9,2)
);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT FK_DEPARTMENTS_EMPLOYEES FOREIGN KEY(MANAGERID) REFERENCES EMPLOYEES,
	CONSTRAINT FK_DEPARTMENTS_SUBDEPT FOREIGN KEY(SUBDEPTOF) REFERENCES DEPARTMENTS;

CREATE TABLE PROJECTS(
PROJECTID CHAR(8) PRIMARY KEY,
DEPTCODE CHAR(5) REFERENCES DEPARTMENTS(CODE),
DESCRIPT VARCHAR(200),
STARTDATE DATE,
STOPDATE DATE,
REVENUE NUMERIC(12,2)
);

CREATE TABLE WORKSON(
EMPLOYEEID NUMERIC(9) REFERENCES EMPLOYEES,
PROJECTID CHAR(8) REFERENCES PROJECTS,
ASSIGNEDTIME NUMERIC(3,2)
);