--Practice--

--commit
BEGIN TRANSACTION T1;
UPDATE VRS
SET INVENTORY=INVENTORY*2;
COMMIT;
SELECT * FROM VRS;

--rollback
BEGIN TRANSACTION T2;
UPDATE VRS
SET INVENTORY=INVENTORY-20;
ROLLBACK;
SELECT * FROM VRS;

--savepoints
BEGIN TRANSACTION T3;

UPDATE VRS
SET INVENTORY=INVENTORY+25;
SELECT * FROM VRS;

SAVE TRANSACTION SPOINT1;

UPDATE VRS
SET INVENTORY=INVENTORY-15;
SELECT * FROM VRS;

SAVE TRANSACTION SPOINT2;

UPDATE VRS
SET INVENTORY=INVENTORY+30;
SELECT * FROM VRS;

SAVE TRANSACTION SPOINT3;
ROLLBACK TRANSACTION SPOINT1;
SELECT * FROM VRS;

--Exercise--
SELECT * FROM DEPARTMENTS;

--1
DELETE FROM DEPARTMENTS
WHERE NAME='ADMINISTRATION' OR NAME IN
(SELECT D1.NAME FROM DEPARTMENTS D1, DEPARTMENTS D2
WHERE D1.SUBDEPTOF=D2.CODE AND D2.NAME='ADMINISTRATION');

DELETE FROM DEPARTMENTS WHERE NAME='ADMINISTRATION' OR SUBDEPTOF IN (SELECT CODE FROM DEPARTMENTS WHERE NAME='ADMINISTRATION'); 

--2
BEGIN TRANSACTION T1;
SAVE TRANSACTION S1;

DELETE FROM DEPARTMENTS
WHERE NAME='ADMINISTRATION' OR NAME IN
(SELECT D1.NAME FROM DEPARTMENTS D1, DEPARTMENTS D2
WHERE D1.SUBDEPTOF=D2.CODE AND D2.NAME='ADMINISTRATION');

SELECT * FROM DEPARTMENTS;
ROLLBACK TRANSACTION S1;
COMMIT;

--Practice--

DECLARE
	@NUM_AGE INTEGER;
BEGIN
	SET @NUM_AGE=20;
	PRINT('MY AGE IS'+STR(@NUM_AGE)); 
END

--using data types
DECLARE
	@WAGES INTEGER,
	@HOURS_WORKED INTEGER=40,
	@HOURLY_SALARY FLOAT=22.50,
	@BONUS INTEGER=150,
	@COUNTRY VARCHAR(100),
	@COUNTER INTEGER=0,
	@DONE BIT,
	@VALID_ID BIT=0; --bit can take 0/1/NULL
BEGIN
	SET @WAGES = (@HOURS_WORKED*@HOURLY_SALARY)+ @BONUS;
	SET @COUNTRY = 'FRANCE';
	PRINT(STR(@VALID_ID));
	PRINT(STR(@WAGES)+' '+@COUNTRY);
END

--try catch
BEGIN TRY
	DECLARE @NUM INT;
	SET @NUM = 5/0;
	PRINT('THIS WILL NOT EXECUTE!');
END TRY
BEGIN CATCH
	SELECT ERROR_NUMBER() AS "ERRORNUMBER",
		ERROR_SEVERITY() AS "ERRORSEVERITY",
		ERROR_STATE() AS "ERRORSTATE",
		ERROR_PROCEDURE() AS "ERRORPROCEDURE",
		ERROR_LINE() AS "ERRORLINE",
		ERROR_MESSAGE() AS "ERRORMESSAGE";
END CATCH

--control constructs
--if
DECLARE
	@v_PurchaseAmount float=1001,
	@v_DiscountAmount float;
BEGIN
	if not(@v_PurchaseAmount<=1000)
		set @v_DiscountAmount = @v_PurchaseAmount*0.05;
	else
		set @v_DiscountAmount = 0;
		print('Discount'+str(@v_DiscountAmount));
END

--while loop
DECLARE
	@v_Counter integer=1;
BEGIN
	while(@v_Counter<5)
	BEGIN
		print('count = '+str(@v_Counter));
		set @v_Counter = @v_Counter+1;
	END
END

--taking input
set @userinput = N'naman'

--Exercise--
SELECT * FROM SYS.OBJECTS
WHERE NAME=N'NDS';

CREATE TABLE TEMP(
NUM_STORE NUMERIC(4),
CHAR_STORE VARCHAR(100),
DATE_STORE DATE);

DECLARE
	@NUM INTEGER,
	@COUNTER INTEGER;
BEGIN
	SET @NUM=N'15';

	IF @NUM<25
		SET @COUNTER=0;
		WHILE(@COUNTER<=@NUM)
		BEGIN
			SET @COUNTER = @COUNTER+1;
			IF(@COUNTER=5)
				INSERT INTO TEMP(NUM_STORE,CHAR_STORE)
				VALUES(@COUNTER,'FIVE');
			ELSE IF(@COUNTER=10)
				INSERT INTO TEMP(NUM_STORE,CHAR_STORE)
				VALUES(@COUNTER,'TEN');
			ELSE IF(@COUNTER=15)
				INSERT INTO TEMP(NUM_STORE,CHAR_STORE,DATE_STORE)
				VALUES(@COUNTER,'FIFTEEN',SYSDATETIME());
			ELSE IF(@COUNTER=20)
				INSERT INTO TEMP(NUM_STORE,CHAR_STORE)
				VALUES(@COUNTER,'TWENTY');
			ELSE
				INSERT INTO TEMP(NUM_STORE)
				VALUES(@COUNTER);
		END
END

SELECT * FROM TEMP;

--Practice--
DECLARE
	@GREETINGS VARCHAR(11)='hello world';
BEGIN
	PRINT(UPPER(@GREETINGS));
	PRINT(LOWER(@GREETINGS));

	PRINT(SUBSTRING(@GREETINGS,1,1));
	PRINT(SUBSTRING(@GREETINGS,LEN(@GREETINGS),1));
	PRINT(SUBSTRING(@GREETINGS,7,5));
	PRINT(SUBSTRING(@GREETINGS,2,LEN(@GREETINGS)));
	PRINT(CHARINDEX('E',@GREETINGS));
END